# Generated by Django 3.2.8 on 2021-10-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('title', models.TextField(default='', verbose_name='titulo')),
                ('subtitle', models.TextField(blank=True, default='', verbose_name='subtítulo')),
                ('type', models.IntegerField(blank=True, default='1', verbose_name='tipo')),
                ('content', models.TextField(blank=True, default='', verbose_name='conteudo')),
                ('status', models.IntegerField(blank=True, default='1', verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('id_pub', models.IntegerField(verbose_name='id_publicacao')),
                ('keyword', models.TextField(blank=True, default='', verbose_name='palavra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
